from sklearn.ensemble import AdaBoostClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC

from keras.models import Sequential, load_model
from keras.layers import Dense, Activation, Dropout
from keras.wrappers.scikit_learn import KerasClassifier

import random
import timeit
import pandas as pd
import numpy as np

from mlearning.scoringMethods import scoring_model

import warnings

warnings.filterwarnings(action="ignore", category=FutureWarning)
# Set Seed

# Data_using
start = timeit.default_timer()

wd = pd.read_csv(r'D:\Data\Grad\test_Work_Data_w_lag.csv')
wd = wd.set_index(wd.columns[0])
wd.index = pd.to_datetime(wd.index)

x = wd[wd.columns[1:]]
y = wd['korclf1']


# Create trainig set, testing set.
x_train, x_test, y_train, y_test = train_test_split(x, y,
                                                    test_size = 0.3,
                                                    shuffle = True) # Split the data. For now no validation set
                                                                    # no random split. so shuffle = false
# Original Data
scale = MinMaxScaler() # Scale the data.
scale.fit(x_train)
x_train_s = pd.DataFrame(scale.transform(x_train), columns = list(x_train.columns))
scale.fit(x_test)
x_test_s = pd.DataFrame(scale.transform(x_test), columns = list(x_test.columns))
date = pd.DataFrame(x_train.index)
date_t = pd.DataFrame(x_test.index)
x_train_s = pd.concat([date, x_train_s], axis = 1)
x_test_s = pd.concat([date_t, x_test_s], axis = 1) # X_train scaled and ready to go
x_train_s = x_train_s.set_index('Unnamed: 0')
x_test_s = x_test_s.set_index('Unnamed: 0') # X_test scaled and ready to go


# Overall
t = [('clf1', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                             max_depth=1, max_features='auto', max_leaf_nodes=None,
                                             min_impurity_decrease=0.0, min_impurity_split=None,
                                             min_samples_leaf=1, min_samples_split=2,
                                             min_weight_fraction_leaf=0.0, n_estimators=100,
                                             n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                             warm_start=False)),
             ('clf2', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                             max_depth=2, max_features='auto', max_leaf_nodes=None,
                                             min_impurity_decrease=0.0, min_impurity_split=None,
                                             min_samples_leaf=1, min_samples_split=2,
                                             min_weight_fraction_leaf=0.0, n_estimators=100,
                                             n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                             warm_start=False)),
             ('clf3', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                             max_depth=3, max_features='auto', max_leaf_nodes=None,
                                             min_impurity_decrease=0.0, min_impurity_split=None,
                                             min_samples_leaf=1, min_samples_split=2,
                                             min_weight_fraction_leaf=0.0, n_estimators=100,
                                             n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                             warm_start=False)),
             ('clf4', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                             max_depth=4, max_features='auto', max_leaf_nodes=None,
                                             min_impurity_decrease=0.0, min_impurity_split=None,
                                             min_samples_leaf=1, min_samples_split=2,
                                             min_weight_fraction_leaf=0.0, n_estimators=100,
                                             n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                             warm_start=False)),
             ('clf5', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                             max_depth=5, max_features='auto', max_leaf_nodes=None,
                                             min_impurity_decrease=0.0, min_impurity_split=None,
                                             min_samples_leaf=1, min_samples_split=2,
                                             min_weight_fraction_leaf=0.0, n_estimators=100,
                                             n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                             warm_start=False)),
             ('clf6', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                             max_depth=6, max_features='auto', max_leaf_nodes=None,
                                             min_impurity_decrease=0.0, min_impurity_split=None,
                                             min_samples_leaf=1, min_samples_split=2,
                                             min_weight_fraction_leaf=0.0, n_estimators=100,
                                             n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                             warm_start=False)),
             ('clf7', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                             max_depth=7, max_features='auto', max_leaf_nodes=None,
                                             min_impurity_decrease=0.0, min_impurity_split=None,
                                             min_samples_leaf=1, min_samples_split=2,
                                             min_weight_fraction_leaf=0.0, n_estimators=100,
                                             n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                             warm_start=False)),
             ('clf8', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                             max_depth=8, max_features='auto', max_leaf_nodes=None,
                                             min_impurity_decrease=0.0, min_impurity_split=None,
                                             min_samples_leaf=1, min_samples_split=2,
                                             min_weight_fraction_leaf=0.0, n_estimators=100,
                                             n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                             warm_start=False)),
             ('clf9', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                             max_depth=9, max_features='auto', max_leaf_nodes=None,
                                             min_impurity_decrease=0.0, min_impurity_split=None,
                                             min_samples_leaf=1, min_samples_split=2,
                                             min_weight_fraction_leaf=0.0, n_estimators=100,
                                             n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                             warm_start=False)),
             ('clf10', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=10, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
             ('clf11', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=11, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
             ('clf12', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=12, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
             ('clf13', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=13, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
             ('clf14', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=14, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
             ('clf15', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=15, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
             ('clf16', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=16, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
             ('clf17', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=17, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
             ('clf18', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=18, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
             ('clf19', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=19, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
             ('clf20', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=20, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
             ('clf21', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=21, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
             ('clf22', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=22, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
             ('clf23', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=23, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
             ('clf24', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=24, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
             ('clf25', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=25, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
             ('clf26', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=26, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
             ('clf27', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=27, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
             ('clf28', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=28, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
             ('clf29', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                                              max_depth=29, max_features='auto', max_leaf_nodes=None,
                                              min_impurity_decrease=0.0, min_impurity_split=None,
                                              min_samples_leaf=1, min_samples_split=2,
                                              min_weight_fraction_leaf=0.0, n_estimators=100,
                                              n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                                              warm_start=False)),
     ('clf30', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
                   max_iter=-1, probability=True, random_state=None, shrinking=True,
                   tol=0.001, verbose=False)), ('clf31', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
                                                             decision_function_shape='ovr', degree=3,
                                                             gamma=0.125, kernel='rbf',
                                                             max_iter=-1, probability=True, random_state=None,
                                                             shrinking=True,
                                                             tol=0.001, verbose=False)),
     ('clf32', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.05555555555555555,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf33', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.03125, kernel='rbf',
                   max_iter=-1, probability=True, random_state=None, shrinking=True,
                   tol=0.001, verbose=False)), ('clf34', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
                                                             decision_function_shape='ovr', degree=3,
                                                             gamma=0.02, kernel='rbf',
                                                             max_iter=-1, probability=True, random_state=None,
                                                             shrinking=True,
                                                             tol=0.001, verbose=False)),
     ('clf35', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.013888888888888888,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf36', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.01020408163265306,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf37', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.0078125, kernel='rbf',
                   max_iter=-1, probability=True, random_state=None, shrinking=True,
                   tol=0.001, verbose=False)),
     ('clf38', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3,
                   gamma=0.006172839506172839,
                   kernel='rbf', max_iter=-1, probability=True,
                   random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf39', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.005, kernel='rbf',
                   max_iter=-1, probability=True, random_state=None, shrinking=True,
                   tol=0.001, verbose=False)),
     ('clf40', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3,
                   gamma=0.004132231404958678,
                   kernel='rbf', max_iter=-1, probability=True,
                   random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf41', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.003472222222222222,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf42', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.0029585798816568047,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf43', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.002551020408163265,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf44', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.0022222222222222222,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf45', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.001953125, kernel='rbf',
                   max_iter=-1, probability=True, random_state=None, shrinking=True,
                   tol=0.001, verbose=False)), ('clf46', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
                                                             decision_function_shape='ovr', degree=3,
                                                             gamma=0.0017301038062283738,
                                                             kernel='rbf', max_iter=-1, probability=True,
                                                             random_state=None,
                                                             shrinking=True, tol=0.001, verbose=False)),
     ('clf47', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.0015432098765432098,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf48', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.0013850415512465374,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf49', SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
                   max_iter=-1, probability=True, random_state=None, shrinking=True,
                   tol=0.001, verbose=False)), ('clf50', SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
                                                             decision_function_shape='ovr', degree=3,
                                                             gamma=0.125, kernel='rbf',
                                                             max_iter=-1, probability=True, random_state=None,
                                                             shrinking=True,
                                                             tol=0.001, verbose=False)),
     ('clf51', SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.05555555555555555,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf52', SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.03125, kernel='rbf',
                   max_iter=-1, probability=True, random_state=None, shrinking=True,
                   tol=0.001, verbose=False)), ('clf53', SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
                                                             decision_function_shape='ovr', degree=3,
                                                             gamma=0.02, kernel='rbf',
                                                             max_iter=-1, probability=True, random_state=None,
                                                             shrinking=True,
                                                             tol=0.001, verbose=False)),
     ('clf54', SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.013888888888888888,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf55', SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.01020408163265306,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf56', SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.0078125, kernel='rbf',
                   max_iter=-1, probability=True, random_state=None, shrinking=True,
                   tol=0.001, verbose=False)), ('clf57', SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
                                                             decision_function_shape='ovr', degree=3,
                                                             gamma=0.006172839506172839,
                                                             kernel='rbf', max_iter=-1, probability=True,
                                                             random_state=None,
                                                             shrinking=True, tol=0.001, verbose=False)),
     ('clf58', SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.005, kernel='rbf',
                   max_iter=-1, probability=True, random_state=None, shrinking=True,
                   tol=0.001, verbose=False)), ('clf59', SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
                                                             decision_function_shape='ovr', degree=3,
                                                             gamma=0.004132231404958678,
                                                             kernel='rbf', max_iter=-1, probability=True,
                                                             random_state=None,
                                                             shrinking=True, tol=0.001, verbose=False)),
     ('clf60', SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.003472222222222222,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf61', SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.0029585798816568047,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf62', SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.002551020408163265,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf63', SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.0022222222222222222,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf64', SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.001953125, kernel='rbf',
                   max_iter=-1, probability=True, random_state=None, shrinking=True,
                   tol=0.001, verbose=False)),
     ('clf65', SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3,
                   gamma=0.0017301038062283738,
                   kernel='rbf', max_iter=-1, probability=True,
                   random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf66', SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.0015432098765432098,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf67', SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.0013850415512465374,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf68', SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
                   max_iter=-1, probability=True, random_state=None, shrinking=True,
                   tol=0.001, verbose=False)),
     ('clf69', SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.125, kernel='rbf',
                   max_iter=-1, probability=True, random_state=None, shrinking=True,
                   tol=0.001, verbose=False)),
     ('clf70', SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.05555555555555555,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf71', SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.03125, kernel='rbf',
                   max_iter=-1, probability=True, random_state=None, shrinking=True,
                   tol=0.001, verbose=False)),
     ('clf72', SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.02, kernel='rbf',
                   max_iter=-1, probability=True, random_state=None, shrinking=True,
                   tol=0.001, verbose=False)),
     ('clf73', SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.013888888888888888,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf74', SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.01020408163265306,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf75', SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.0078125, kernel='rbf',
                   max_iter=-1, probability=True, random_state=None, shrinking=True,
                   tol=0.001, verbose=False)),
     ('clf76', SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.006172839506172839,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf77', SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.005, kernel='rbf',
                   max_iter=-1, probability=True, random_state=None, shrinking=True,
                   tol=0.001, verbose=False)),
     ('clf78', SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.004132231404958678,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf79', SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.003472222222222222,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf80', SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.0029585798816568047,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf81', SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.002551020408163265,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf82', SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.0022222222222222222,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf83', SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.001953125, kernel='rbf',
                   max_iter=-1, probability=True, random_state=None, shrinking=True,
                   tol=0.001, verbose=False)),
     ('clf84', SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.0017301038062283738,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf85', SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.0015432098765432098,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False)),
     ('clf86', SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
                   decision_function_shape='ovr', degree=3, gamma=0.0013850415512465374,
                   kernel='rbf', max_iter=-1, probability=True, random_state=None,
                   shrinking=True, tol=0.001, verbose=False))
      ]

votingClf = VotingClassifier(t)

# Adaboost itself

for i in range(1, len(t)+1):
    adaboost = AdaBoostClassifier(base_estimator=votingClf, n_estimators=i, algorithm='SAMME')
    adaboost.fit(x_train_s, y_train)
    y_pred_adaboost = adaboost.predict(x_test_s)
    acc_adaboost = scoring_model(y_test, y_pred_adaboost)
    print(acc_adaboost.sensitivity(), acc_adaboost.specificity(), acc_adaboost.accuracy())
